CC = gcc
CFLAGS = -Wall -Wextra -O2
TARGET = x3d-toggle-c
SRC = x3d-toggle.c
PREFIX = /usr
BINDIR = $(DESTDIR)$(PREFIX)/bin
CONFDIR = $(DESTDIR)/etc
SHAREDIR = $(DESTDIR)$(PREFIX)/share/x3d-toggle
POLKITDIR = $(DESTDIR)$(PREFIX)/share/polkit-1/actions
SYSTEMDDIR = $(DESTDIR)$(PREFIX)/lib/systemd/user
APPDIR = $(DESTDIR)$(PREFIX)/share/applications
LICENSESDIR = $(DESTDIR)$(PREFIX)/share/licenses/x3d-toggle

all: $(TARGET)

$(TARGET): $(SRC)
	$(CC) $(CFLAGS) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)

install: $(TARGET)
	install -d $(BINDIR)
	install -m 755 $(TARGET) $(BINDIR)/$(TARGET)
	install -m 755 x3d-control $(BINDIR)/x3d-control
	install -m 755 x3d-daemon $(BINDIR)/x3d-daemon
	
	install -d $(CONFDIR)
	install -m 644 x3d-toggle.conf $(CONFDIR)/x3d-toggle.conf
	
	install -d $(SHAREDIR)
	install -m 644 assets/ryzen.jpeg $(SHAREDIR)/ryzen.jpeg
	
	install -d $(POLKITDIR)
	install -m 644 org.x3dtoggle.policy $(POLKITDIR)/org.x3dtoggle.policy
	
	install -d $(SYSTEMDDIR)
	install -m 644 x3d-auto.service $(SYSTEMDDIR)/x3d-auto.service

	install -d $(LICENSESDIR)
	install -m 644 LICENSE $(LICENSESDIR)/LICENSE
	
	@echo "Note: Desktop file is not installed by Makefile (generated by PKGBUILD)."
	@echo "Installed to $(PREFIX)"

uninstall:
	rm -f $(BINDIR)/$(TARGET)
	rm -f $(BINDIR)/x3d-control
	rm -f $(BINDIR)/x3d-daemon
	rm -f $(CONFDIR)/x3d-toggle.conf
	rm -rf $(SHAREDIR)
	rm -f $(POLKITDIR)/org.x3dtoggle.policy
	rm -f $(SYSTEMDDIR)/x3d-auto.service
	rm -rf $(LICENSESDIR)
	@echo "Uninstalled from $(PREFIX)"

.PHONY: all clean install uninstall
